### ISSUE TITLE
Link to ETF Design Report

### ISSUE THREAD

**Issue by michellutz** [etf-validator/governance#10]
ii to add a link to the document on JoinUp once it has been published including a note that the documents specifies the design and does not document the current ETF version.

**Comment by jonherrmann** [comment]
Should we refer to this one?
https://joinup.ec.europa.eu/document/inspire-test-framework-design-report

I suggest to reference this in the Developer manuals section [here](http://docs.etf-validator.net/v2.0/index.html) as

- ETF system structure and concepts (initial design, does not reflect the current developments)

**Comment by michellutz** [comment]
OK. Maybe say "... (initial design, does not reflect all current developments)"
