### ISSUE TITLE
Simplified UI for starting tests

### ISSUE THREAD

**Issue by michellutz** [etf-validator/governance#17]
# Background and Motivation:
Several MS experts and representatives have reported that the current user interface for selecting test suites and starting tests is considered difficult, especially for occasional or novice users, who do not understand the notion of conformance classes and do not know which ones to select.

# Proposed change
A simplified UI for starting tests should be added to the ETF, in addition to the current (more expert) UI, similar to the one of the Geoportal's evaluation tool (http://inspire-geoportal.ec.europa.eu/validator2/). In the UI, the user can simply upload a (link to a) resouce. The ETF should then figure out the type of resource (e.g. WMS-based view service, Atom-based download service, data set containing AD and BU features) and offer and pre-select in a dialogue/page all conformance classes that could be tested on the identified resource to the user, who can then choose to deselect one or several conformance classes, before launching the test.

# Alternatives
A easier-to-implement way to simplify the UI could be to simply offer known resource types & sub-types (e.g. view-WMS, view-WMTS, download-Atom, download-WFS, data set/spatial object types) and pre-select all tests based on the user's selection (rather than analysis of the resource).

# Funding
The JRC is prepared to fund this through the contract with Bilbomatica, Guadaltel et al.

# Additional information
- SK (Martin Tuchyna, Tomas Kliment) have implemented a simple user interface accessing the ETF's REST interface. Their code (if available as OS) could be a starting point.

**Comment by cportele** [comment]
JRC to review. See minutes of the 3rd SG meeting.

**Comment by jenriquesoriano** [comment]
To do: 
- Check with the INSPIRE community the approach to simplify the user interface 
- Analyze if the API complies with the user requirements
- Assess if this development can be incorporated to the ETF community

**Comment by carlospzurita** [comment]
We analyzed the Swagger documentation on the ETF API, and we think that this improvement can be achieved, with some additional code on the backend. 

An alternative initial menu could be developed, in addition to the current Start Test tab, following the same structure of the Geoportal's evaluation tool. Using the web API, a TestObject can be created via URL or via source file, using a POST request to /v2/TestObjects. After that, the TestObject can be analyzed using XQuery to detect the type of resource, and offer the user some presets of TestSuites. Then the TestRun could be started as usual using the POST request to /v2/TestRuns, referencing the TestSuites selected and the TestObject previously created.

The collection of preset tests should be defined for each type of resource, incoporating some feedback from the INSPIRE community. Maybe the TestReports could also give some insight into what tests are more often selected depending on the type of resource.

**Comment by MarcoMinghini** [comment]
Closed as agreed in the [SG meeting 19 on 2020-01-21](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20200121.md).
