### ISSUE TITLE
Add a Rerun button

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#18]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:
Moved from etf-validator/etf-webapp#62. Add a rerun button to facilitate re-testing test objects.

Scenario 1:
A user wants to test a dataset. She/he chooses an ETS and uploads the file. After executing the test and reviewing the test report, she/he wants to fix issues in his dataset and quickly rerun the test with the fixed file without navigating again through the dialogs. In the rerun dialog the ETS(s) and other parameters are taken from the previous test run. The new file must be uploaded.

Scenario 2:
Similar to scenario 1, but the user tests a web service. After inspecting the test report, the user fixes the web service. She/he wants to rerun the test against the same service again. In the dialog the ETS(s), the other parameters and the service endpoint are taken from the previous test run, but might be changed by the user.

# Proposed change
- A small gear icon could be implemented in the upper right corner of the test reports.

<img width="1165" alt="screenshot 2018-08-06 19 49 54" src="https://user-images.githubusercontent.com/13570741/43732415-f9f03230-99b1-11e8-9db9-a5e1eecee461.png">

- Clicking on the button could open the rerun test dialog.

- It might be better to hide the icon in a downloaded report.

- To not collide with developments from EIP #17 and to be reusable in an alternative user interface, the logic should not be implemented in the UI but in the Test Run REST controller.

# Alternatives
Implementing the logic in the UI would be easier to achieve. Another option could be to just show the button in the test report overview page, next to the download button. The disadvantage would be that the user has to go back from the test report.

# Funding
Taken from etf-validator/etf-webapp#62 . Still funded by JRC?

**Comment by cportele** [comment]
JRC to review the EIP and update as necessary. See minutes of the 3rd SG meeting.

**Comment by carlospzurita** [comment]
Just to clarify this issue, please find below the possible implementation for the re-run button.
This feature has been developed as part of the following pull-request that can be found here https://github.com/etf-validator/etf-webapp/pull/158

The functionality of this button works as follows:

- The button appears in every Test Report, as the control "Run test again" for this report
![remote](https://user-images.githubusercontent.com/10537778/44720495-481eec00-aac7-11e8-9f90-ca337e6c6aa1.png)
![local](https://user-images.githubusercontent.com/10537778/44720588-8c11f100-aac7-11e8-8d5e-6714f4e2fb29.png)

- If the source is a local file, the webapp would prompt the user to provide the source again
![upload_modified_file](https://user-images.githubusercontent.com/10537778/44720644-b06dcd80-aac7-11e8-84a6-16b77adb8249.png)

- Alternatively, if the source is a remote file, the test run would be launched again using the same URL
![rerun_automatically](https://user-images.githubusercontent.com/10537778/44720693-d8f5c780-aac7-11e8-9085-8401f24cbd07.png)

This button can be moved to other place if needed, without altering the functionality.

**Comment by jonherrmann** [comment]
@carlospzurita thanks for clarifying.

When I checked the PR, I did not notice in my local deployment, that I was rerunning a metadata ETS that referenced a remote file. I expected a dialog to appear.

Of course, the implemented makes sense.

**Comment by jonherrmann** [comment]
I merged the PR two days ago but found an issue today: the rerun button does not work if the test object has been cleaned up and no longer exists.

There should be no need to [revert](https://github.com/etf-validator/etf-webapp/pull/206) the PR, but we should fix this issue soon.
