### ISSUE TITLE
Add new result status 

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#24]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:
At the moment the ETF core defines nine different status for describing the 
results of a test:

- PASSED
- FAILED
- SKIPPED
- NOT_APPLICABLE
- INFO
- WARNING
- UNDEFINED
- PASSED_MANUAL
- INTERNAL_ERROR

In a test, we would like to output an advisory message with a status which 
is not reflected in the semantics of the INFO or the WARNING status. Since this 
functionality can not be defined in the ETS, but only in the ETF core, we would 
like to add the status there.

# Proposed change
We would like to add a status NOTICE, which can be classified by the severity
between INFO and WARNING. While a WARNING message should be fixed by the user
in the short term, a NOTICE message can be tolerated by the user but should be 
fixed in the medium term.

The aggregation of the message would be very similar to the INFO and WARNING
message: two test results with an INFO and a NOTICE status would be aggregated 
to a NOTICE status in the next higher result structure, NOTICE and WARNING would
be aggregated to WARNING.

# Alternatives
You could make all states and aggregation configurable. On the one hand that 
would require much more effort and on the other hand it is not clear how ETSs which are 
using different status could be exchanged.

# Funding
Full funding available.

# Additional information
- This EIP is backwards compatible with existing ETSs. 
- Would require modifications in the [ETF core](https://github.com/etf-validator/etf-core/blob/master/src/main/java/de/interactive_instruments/etf/dal/dto/result/TestResultStatus.java) and [ETF SPI](https://github.com/etf-validator/etf-spi/blob/master/src/main/java/de/interactive_instruments/etf/testdriver/AbstractTestCollector.java#L208)

**Comment by cportele** [comment]
Update according to the discussion in the 4th SG Meeting:

> * The current status codes should be clearly defined, in order to better understand why a new code is needed.
> * It should be avoided to keep adding new status codes, if the existing ones can be used.

**Comment by cportele** [comment]
The EIP is no longer needed, the requirement was solved differently.
