### ISSUE TITLE
Show ETS dependencies in user view

### ISSUE THREAD

**Issue by michellutz** [etf-validator/governance#30]
# Background and Motivation:
When you run a test that has dependencies, they are also run. However, the user is not warned of this until the test begins to run.

This issue is related to etf-validator/etf-webapp#68.

# Proposed change
When selecting an ETS with the use flip switch, all dependent ones should be selected automatically.

# Alternatives
Add this functionality to ExecutableTestSuiteView.js

# Funding
TBC

**Comment by michellutz** [comment]
If a conformance class has dependencies on other conformance classes, these should also be automatically selected in the user interface. The automatically selected conformance classes should be greyed out, so that they cannot be individually deselected.

Alternatively, a pop-up window could be shown in addition informing the user that there are dependencies and that these will executed in addition.

**Comment by michellutz** [comment]
For the implementation, we need to understand where the information on the ETS dependencies can be obtained.

**Comment by cportele** [comment]
See [here](https://docs.etf-validator.net/v2.0/Developer_manuals/Developing_Executable_Test_Suites.html#_dependencies) for how the dependencies are represented in the XML of the ETSs

**Comment by jonherrmann** [comment]
Also see this:
https://github.com/etf-validator/etf-spi/blob/b2301fad388929671bf369e8e57a8b27e1f72948/src/test/java/de/interactive_instruments/etf/DependencyResolverTest.java

**Comment by carlospzurita** [comment]
The phases and experiments for this EIP can be these:
1. Deploy on a single EC2 instance and ensure ETF works properly
2. Develop the module to decouple the storage from the service, which will act as an interface.
3. Once given an S3 instance, connect this interface to AWS for retrieving and persisting files
4. Carry out stress tests to check if one instance of the service, with the external storage, is sufficient for running the service
5. If needed add capabilities on the ETF cloud deployment to escalate and create instances on demand. 
6. Develop the necessary changes to match instances and persistence

**Comment by michellutz** [comment]
This is related to issue #28. Once the requirements are further defined, a common solution should be developed for both issues.

**Comment by MarcoMinghini** [comment]
Following discussion with the members of MIWP Action 2017.4 (see [here](https://github.com/inspire-eu-validation/community/issues/6)), it was agreed that:

- the improvement to the "Start test" tab, to automatically select (grey out) all the conformance classes dependent on the conformance class(es) selected by the user, has a high priority for implementation and should be moved forward.
- the improvement to the "Configure Test Run" window has a low priority, so it can be discarded for the time being.

Funding is ensured by the JRC.

**Comment by MarcoMinghini** [comment]
From SG meeting 9: In addition to direct dependencies, information about transitive dependencies is available, but needs to be processed in the ETF.

**Comment by MarcoMinghini** [comment]
In the new UI of the [INSPIRE Reference Validator](https://inspire.ec.europa.eu/validator/test-selection/index.html), the dependence between conformance classes is managed through the use of checkboxes.

Therefore, this proposal is no longer relevant for us. Unless there are different views, we suggest to close it.
