### ISSUE TITLE
Password field does not hide the password

### ISSUE THREAD

**Issue by michellutz** [etf-validator/governance#35]
# Background and Motivation
In the configure test run window, there is a password field. The password that you enter there is visible. This could be a security vulnerability, especialy if you work in a public space.

# Proposed change
The password field must hide the password.

# Alternatives
Change the input start-tests-password type to "password".

# Funding
TBD

**Comment by jenriquesoriano** [comment]
This is considered to be a bug and will be reported as an issue in the etf-webapp repository.

**Comment by jonherrmann** [comment]
Has been merged into the next branch: https://github.com/etf-validator/etf-webapp/pull/190

Since this was classified as a bug and not an EIP, I hope nobody will mind if I close it without consulting the SG.
