### ISSUE TITLE
Provide a list of contributors who accept and agree to the Contributor License

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#38]
Initially, the following GitHub usernames will be whitelisted for PRs:

- michellutz 
- robsgnao 
- boehmesven 
- jechterhoff 
- cportele 
- jonherrmann

JRC, please provide a list of additional contributors.

**Comment by MarcoMinghini** [comment]
@jonherrmann this is not relevant anymore and can be safely closed.
