### ISSUE TITLE
Keep sticky header visible in the report page

### ISSUE THREAD

**Issue by jenriquesoriano** [etf-validator/governance#40]
**ETF Improvement Proposal (EIP)**

Keep the sticky header visible also in the report page offering the user the option to directly access to the main parts of the ETF

# Background and Motivation:

When you are working in the report page it might be useful to get to the rest of parts of the ETF directly by using the sticky header instead of going back to the report overview page

# Proposed change

The sticky header will be included in the report page so you can navigate directly through the ETF

# Alternatives
The report can be opened in a separate tab, so the user might change between tabs and come back to the test reports overview page

# Funding
TBD

# Additional information
N/A

**Comment by carlospzurita** [comment]
The easier option to implement this is to open the report in a new tab. If it is required to keep all the application in one tab, then the TestRun2DefaultReport.xsl template, on the etf-bsxds module, should be modified to add the ETF header. Another option would be to intercept the HTML on the TestResultController class to add the header with the proper URL.

**Comment by MarcoMinghini** [comment]
Closed as agreed in the [SG meeting 19 on 2020-01-21](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20200121.md).
