### ISSUE TITLE
Replace "tests to execute" regex with selection dialogue

### ISSUE THREAD

**Issue by michellutz** [etf-validator/governance#41]
# Background and Motivation:
The "tests to execute" regular expression in the user interface is difficult to use for non-expert users. 

# Proposed change
Replace the "tests to execute" regular expression with a checkbox named "select tests to execute". If the checkbox is selected, launch another dialogue where the user can (de)select some of the tests from the conformance classes selected in the first step.

The regex option would still be available through the API. 

# Alternatives
n/a

# Funding
TBD

# Additional information
This is an optional section for additional information. These could include,
for example:
- the impact of this EIP, known risks or compatibility issues on
deployments and/or Executable Test Suites.
- (time) constraints, if this EIP is full or partial funded

**Comment by jenriquesoriano** [comment]
To do: 
- Prepare some mockups
- Discuss with the INSPIRE validation community

**Comment by carlospzurita** [comment]
In this mockup we present a possibility of displaying this dialogue in tree form
![imagen](https://user-images.githubusercontent.com/10537778/47280387-82dc6680-d5d6-11e8-8b92-31e2dd04d9e6.png)
This tree would have more collapsible levels, as the Test Suites have more nested tags of TestModules, TestCases, TestSteps and Assertions.

**Comment by michellutz** [comment]
Alternatively, the initial dialogue could just have a checkbox named "select tests to execute".

If the checkbox is selected, another dialogue would be launched where the user can (de)select some of the tests from the conformance classes selected in the first step. This could look something like this (obviously in a proper dialogue):

![select tests to execute](https://user-images.githubusercontent.com/5517424/47734716-2975d680-dc6b-11e8-848c-bdc2028b35d5.jpg)

**Comment by michellutz** [comment]
I looked again at the current behaviour, and discovered that the "Selected Test Suites" part only occurs when the "Test Suites" button is selected. In this case, we don't need a separate dialogue (I removed my comment on this), but could use the proposal made by @carlospzurita. Maybe the button should then be renamed "Selected tests" or "Select tests".

I would not include the possibility to select TestSteps or Assertions, but stop at TestCases.

Do we need to consider dependencies between test cases here or only between conformance classes?

Another question: should the optional parameters (now only "tests to execute") remain if the option with checkboxes is implemented or should this only be available through the API?

**Comment by carlospzurita** [comment]
One approach could be to only display on the tree the TestCases, for easier selection, then leave the optional parameters button as it is now to let more expert users fine tune the TestSteps and Assertions. Then, merging the proposal from https://github.com/etf-validator/governance/issues/30, the Conformance Classes can be divided between "Required" and "Selected".

**Comment by cportele** [comment]
> I would not include the possibility to select TestSteps or Assertions, but stop at TestCases.

We have a requirement that the Test Run Templates and the UI to edit/save them locally (see also #27, #28) supports switching conformance classes, test cases and test assertions off. That is, if we want to have one UI then it would have to go beyond the test cases. 

> Do we need to consider dependencies between test cases here or only between conformance classes?

Good point. I think, it would be hard to understand why dependencies between conformance classes are taken into account, but not between test cases?

> Another question: should the optional parameters (now only "tests to execute") remain if the option with checkboxes is implemented or should this only be available through the API?

As it is a parameter, it is either accessible through both the (standard) UI and the API or not at all. In general I would remove the parameter once there is a more intuitive UI. That is at least what we plan to do in other (non-INSPIRE) ETSs.

**Comment by MarcoMinghini** [comment]
Closed as agreed in the [SG meeting 19 on 2020-01-21](https://github.com/etf-validator/governance/blob/master/Meetings/SG/20200121.md).
