### ISSUE TITLE
EIP process

### ISSUE THREAD

**Issue by michellutz** [etf-validator/governance#51]
[I move this discussion from the e-mail thread to an issue, to make it easier to reference]

Dear Clemens & Jon,

we conituned our iscussion about the EIP process yesterday after our SG meeting and tried to visualise our understanding of the process in the attached flowchart. It includes the discussion and agreement of ideas as we discussed yesterday as a possible (but not necessary) first step before proposing a fully-fledged (and well analysed) EIP.

If you agree to this understanding, we would propose to

- rename EIP-draft label to idea (or EIP-idea)
- remove the SG:in discussion and SG:EIP accepted statuses in the board (the EIP should only be accepted, if funding is available for it)
- rename SG:draft to EIP creator:Draft EIP idea
- rename the Feedback / revision required by EIP creator to EIP creator: Draft/refine EIP and move it to the left as step 2.

Does this make sense?

Cheers,
Marco and Michael

![eip flowchart](https://user-images.githubusercontent.com/5517424/48017353-625ff080-e12e-11e8-91aa-3f600d3ecc43.jpg)

**Comment by michellutz** [comment]
[Reply by Jon on 2018-10-05]

Hi Michael, all,

ok, when we decide to remove the "SG: EIP accepted” column, we should clearly state in the EIP template that if funding is not available, the EIP is rejected. Does this mean that partially funded EIPs are rejected if no other SG member decides to participate in the funding? 

In general, I have no objections but I'm wondering if it would not be easier to drop the EIP-idea or draft label and set up the columns to just drag the EIPs from left to right?

With the columns:
Creator: Draft EIP idea | SG: EIP idea in discussion | Creator: Refine idea into EIP | SG: Refined EIP in discussion 

Best regards
Jon

**Comment by cportele** [comment]
Potential columns: 

* Proposer: Draft/refine EIP
* SG: discussion 
* TC: analysis
* TC: in release planning
* TC: scheduled for release
* Implemented

**Comment by cportele** [comment]
Proposer assigns "EIP-idea" or "EIP" and moves it to "SG: discussion" when ready for discussion. If it is an idea and the SG approves it, it will change the tag to "EIP" and moves it back to "Proposer: idea/draft". Once the EIP is ready the proposer moves it (again, if it was an idea before) to "SG:discussion". If the draft needs further updates, it goes back to the first column.

An EIP that is technically approved, but does not have full funding will remain in "SG: discussion". Or probably it should it go back to "Proposer: Draft/refine EIP" until funding is secured? Create an "approved" or "needs funding" tag?

**Comment by michellutz** [comment]
We agreed in the SG meeting today to have the following tags:

- EIP-draft (for EIPs in idea/draft stage)
- EIP (for mature EIPs, ready for SG approval)
- EIP-approved (for EIPs approved by the SG)

We decided not to have an "needs-funding" tag for the time being. This might be added in the future, if there is a need to filter issues for the funding aspect.
