### ISSUE TITLE
New module for testing topological errors in spatial data

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#59]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:

As part of a german project, a library for checking topological errors has been developed, which we would like to add to the ETF ecosystem. The library is currently available in this [repository](https://github.com/interactive-instruments/etf-topox). The library is licensed under the EUPL 1.2.

The developer documentation is a [here](https://github.com/interactive-instruments/etf-topox/blob/next/docs/Developer_documentation.md).

# Proposed change

Move the library to the etf-validator organisation. As it will be part of the BaseX testdriver, it will be integrated into the [etf-bsxtd](https://github.com/etf-validator/etf-bsxtd) repository.

# Alternatives

No further considerations

# Funding

Yes

# Additional information

none

**Comment by MarcoMinghini** [comment]
**SG meeting 24 (2020-08-06)**
It is agreed to accept the EIP and move it under _TC: scheduled for release_ in the [EIP project board](https://github.com/orgs/etf-validator/projects/2). The EIP will be included in the next release of the ETF.

**Comment by jonherrmann** [comment]
Implemented in [Version 2.1.0](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
