### ISSUE TITLE
Adding support for WCS ETS

### ISSUE THREAD

**Issue by carlospzurita** [etf-validator/governance#66]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:
As for WMS and WMTS, the validator would need to be adapted to show the developments in the WCS ETS.

# Proposed change
Add the supported test object types for SOAPUI tests, as in the pull requests https://github.com/etf-validator/etf-sui-ae/pull/4 and https://github.com/etf-validator/etf-webapp/pull/194 . We need to add the EIDf897f313-55f0-4e51-928a-0e9869f5a1d6 on the etf-sui-mapper Types.java class, and on the StartTestView.js script for starting the test run and show the service endpoint input.

# Alternatives

# Funding
Funding is provided by JRC.

# Additional information

**Comment by jonherrmann** [comment]
## Alternative for the UI

Use the base types for service tests, so that we do not need to add other types manually in the future. This would require that the base types and the relationship to the subtypes "somehow" be known in the user interface.

**Comment by jonherrmann** [comment]
Implemented in [Version 2.1.0](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
