### ISSUE TITLE
Simplify the customization of the ETF header/footer

### ISSUE THREAD

**Issue by MarcoMinghini** [etf-validator/governance#67]
# Background and Motivation:

> Explain the problem behind this proposal. If the problem has already been discussed externally, please add a link. Source code or data snippets, diagrams, graphics that illustrate the problem are welcome.

The appearance of the INSPIRE ETF instance does not currently resemble the usual EC/JRC one, so the idea would be to have an easy way to customize the appearance of the ETF by changing the header and footer.

# Proposed change

> Explain what should be changed in the software. Mockups, screenshots, diagrams or other graphics are welcome.

This would require changing the layout.html on the ETF webapp (e.g. adding the logos of INSPIRE and JRC, the relevant links and changing the background color). We may have to add some values on the View.java class to parametrize the contents of the header and the footer, but it should not be any more complex than that.

# Funding

> Is there full or partial funding available for implementing this proposal?

Funding is ensured by the JRC.

**Comment by jonherrmann** [comment]
Server Side Includes are usually used for such customizations. From my point of view this is the preferable alternative, which does not require any changes to the software.

**Comment by carlospzurita** [comment]
In the spirit of keeping the customizations separated from the core application, one alternative to Server Side Includes could be conditional replacement of Thymeleaf fragments. As with the [branding text](https://github.com/etf-validator/etf-webapp/blob/a47555a12b4bbfc0e5f6755f774cf029a7aec2ba/src/main/webapp/layout.html#L26) or the [contact information](https://github.com/etf-validator/etf-webapp/blob/a47555a12b4bbfc0e5f6755f774cf029a7aec2ba/src/main/webapp/layout.html#L63), the fragments to replace on the layout.html could be selected on the configuration file to point to custom  templates, then checking if these properties have been set up, and use th:replace to add the templates.

This improvement would need changes on:
- Webapp Frontend
- Webapp backend

**Comment by jonherrmann** [comment]
Contact information, disclaimer, etc. are legally binding information that public deployments must provide and are therefore information that can be configured.

> ... could be selected on the configuration file to point to custom templates, then checking if these properties have been set up, and use th:replace to add the templates.

We don't understand how this can work effectively with logos, fonts, etc. when only single entry points are replaced with Thymeleaf: in order to realise a complete corporate design, many th:replace points would probably be necessary, which would also have to be maintained and provided with new tests.

Smaller adjustments could be realised with SSI. A corporate design should be realised in a separate user interface to keep side effects away from the "standard" user interface.

**Comment by michellutz** [comment]
To be discussed in the SG: Should the possibility to customise the header and footer of the web user interface with corporate "branding" be part of the master branch or be implemented in an additional (custom) UI not part of the master branch? We believe it should be the former.

**Comment by MarcoMinghini** [comment]
As agreed during SG meeting 12, the issue is closed. JRC will work to develop its own customization of the ETF interface and share the outcome with the SG afterwards.
