### ISSUE TITLE
Migrate to Java 11

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#71]
**ETF Improvement Proposal (EIP)**

Note: EIP Blocked by SoapUI, see additional Information.

# Background and Motivation:

Java SE 8 is going through the "End of Public Updates process for legacy releases" and will no longer be supplied with security patches after December 2020.

In the near future, Java 8 will no longer be available in some Linux distributions.  One distribution that has a very conservative update policy is Debian. The next Debian release 10 will use version 11 as default Java Runtime Environment and the release is planned for Summer 2019. It will probably take some time for end users and organizations to upgrade to newer distributions such as Debian 11, but we should have that on the radar.

# Proposed change

Procedure: update one component after another, start with the critical ones (see SoapUI in the Additional Information section). Check if we need better test coverage for certain used important libraries.

# Alternatives

# Funding

# Additional information

- SoapUI (test driver for web service tests) : There have been problems in the past upgrading the SoapUI test driver from Java 7 to Java 8. There have been some complex Groovy Runtime dependencies that required to wait for Smartbear to release a Java 8 compiled version. The last SoapUI release has been made in 2016. At the moment it is unclear whether an update is possible at all.

- BaseX 9.1 is baked with Java 8. However, prototypes have shown that it works when ETF is built with J11. [Update 07.05.2019: BaseX now supports the new Java versions natively]

- Gradle 5.x is required in order to work with Java 11. The updated etf-bda version 2 is already working with Gradle 5.3

**Comment by michellutz** [comment]
@df-git Please investigate situation in JRC and provide feedback here. Thanks!

**Comment by df-git** [comment]
We are using Open JDK since for the Oracle JDK the license is required.
You can choose the JDK vesrion that best fits but if it is not the system one you need to keep it updated.

**Comment by jonherrmann** [comment]
Implemented in [Version 2.1.0](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
