### ISSUE TITLE
Adding support for CSW ETS

### ISSUE THREAD

**Issue by carlospzurita** [etf-validator/governance#78]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:
As for WCS and SOS, the validator would need to be adapted to show the developments in the CSW ETS.

# Proposed change
Add the supported test object types for SOAPUI tests, as in the pull requests https://github.com/etf-validator/etf-sui-ae/pull/5 and https://github.com/etf-validator/etf-webapp/pull/199 . We need to add the EID4b0fb35d-10f0-47df-bc0b-6d4548035ae2 on the etf-sui-mapper Types.java class, and on the StartTestView.js script for starting the test run and show the service endpoint input.

# Alternatives

# Funding
Funding is provided by JRC.

# Additional information

**Comment by jonherrmann** [comment]
OK

**Comment by jonherrmann** [comment]
Implemented in [Version 2.1.0](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
