### ISSUE TITLE
make reports available in machine parsable format

### ISSUE THREAD

**Issue by pvgenuchten** [etf-validator/governance#79]
# Background and Motivation:
The current html report is quite hard to read by machines. There are various use cases of machines wanting to parse the report. 
- If a software integrates a remote validation and wants to present the results of the validation within the current environment ([GeoNetwork](https://github.com/geonetwork/core-geonetwork/pull/2444))
- If the full content of an SDI or catalogue is validated at intervals, and reports should be created with clustering on specific test cases failing ([INSPIRE Dashboard](https://inspire-dashboard.eea.europa.eu))

# Proposed change
I think two approaches are possible:
- Add a parameter to the request to request a specific encoding for the report, in this scenario machines would ask for json or xml.
- Add microdata (or RDFa) to the html report, so the report can be parsed using a microdata parser.

# Funding
Not yet.

**Comment by michellutz** [comment]
@pvgenuchten Please have a look at the API of the ETF (e.g. at http://inspire-sandbox.jrc.ec.europa.eu/etf-webapp/swagger-ui.html). You should already be able to retrieve all the relevant information in JSON or XML.

**Comment by pvgenuchten** [comment]
Thanx for the hint Michael, I will give it a look
