### ISSUE TITLE
Add Java Client to ETF validator organisation

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#87]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:
As part of a german project, a Java client was developed, which we would like to add to the ETF ecosystem. The library is currently available [in this repository](https://github.com/interactive-instruments/etf-client). The library is licensed under the EUPL 1.2.

# Proposed change
Move https://github.com/interactive-instruments/etf-client to https://github.com/etf-validator/etf-client

# Alternatives
No further considerations

# Funding
The library was funded by terrestris and the german Federal Agency for Cartography (BKG) as part of the development of the GDI-DE Testsuite.

# Additional information
none

**Comment by cportele** [comment]
Approved in the 20th meeting
