### ISSUE TITLE
Add etf-result-checker to ETF validator organisation

### ISSUE THREAD

**Issue by jonherrmann** [etf-validator/governance#92]
**ETF Improvement Proposal (EIP)**

# Background and Motivation:

ii has developed a [tool](https://github.com/interactive-instruments/etf-result-checker) for checking the results of an ETF validator instance. The tool can provide automated support for the ETF software quality assurance process.

The usage is describe in the [Readme](https://github.com/interactive-instruments/etf-result-checker/blob/master/Readme.md).

The tool is currently limited to test suites using the BaseX test driver, because assertion names have to be unique for each test run. This is not the case for SoapUI-based test suites.

# Proposed change

Move https://github.com/interactive-instruments/etf-result-checker to https://github.com/etf-validator/etf-result-checker

# Alternatives

No further considerations

# Funding

Yes

# Additional information

none

**Comment by cportele** [comment]
SG meeting 2020-05-07:

* Version separately, release first version as 1.0.0
* add reference to the ETF documentation how to develop ETSs

**Comment by jonherrmann** [comment]
Implemented in [Version 2.1.0](https://github.com/etf-validator/etf-webapp/releases/tag/2.1.0)
